[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect API requests to the serverless functions
[[redirects]]
  from = "/api/download-binary/*"
  to = "/.netlify/functions/download-binary/:splat"
  status = 200

[[redirects]]
  from = "/api/download/*"
  to = "/.netlify/functions/download/:splat"
  status = 200

# Fallback for all other routes to the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
